### ISSUE TITLE
Please create a new PyPI release

### ISSUE THREAD

**Issue by mpasternak** [arteria/django-favicon-plus#18]
Current version in pipit (0.0.6) does NOT reflect recent changes (shows that "" comment). 

Please update version number and make a new release.

If busy, please give me commit privs to this repo and to pypi (my e-mail is michal.dtz@gmail.com) and I'll take care of it.

**Comment by walterrenner** [comment]
Hi @mpasternak.

Lastest changes are available on PyPI in version 0.0.7

**Comment by mpasternak** [comment]
Thanks!
